export const TOOLTIPS = {
  spot: "Index spot price at snapshot time",
  totalGex: "Net dealer gamma exposure per 1% move (Bn$)",
  regime: "LONG gamma dampens moves; SHORT gamma can amplify",
  gammaFlip: "Strike where cumulative GEX crosses zero — pin/magnet level",
  callWall: "Strike with largest positive GEX — resistance magnet",
  putWall: "Strike with largest negative GEX — support magnet",
  vix: "CBOE Volatility Index at snapshot",
  ivRank: "Implied volatility rank (0–100%)",
  flowBuyRatio: "Share of flow classified as buy-side",
  flowAggressiveness: "Flow aggressiveness score from UW flow data",
  flowEvents: "Count of options flow events in the window",
  flowNetDeltaGex: "Net delta GEX from flow events (Bn$)",
  eventRisk: "Composite macro event risk score",
  netDelta: "Net dealer delta exposure (Bn$)",
  netCharm: "Net charm exposure (Bn$)",
  netVanna: "Net vanna exposure (Bn$)",
  expectedMove: "Expected 1-day move as % of spot",
} as const;
